blank_issues_enabled: false
contact_links:
  - name: ğŸ§ QF-Wonder QQç¾¤
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=ewXjxbCPcrGPEYLrrBDuG_Qr4-1ysDP0&authKey=iBmf3waFztVg4VyNlL0%2FpUmkrymbmwAUTS8S47FWFHFnqkHOkmAuTyCSGU%2FbugiQ&noverify=0&group_code=787344812
    about: è®°å¾—è¦åŠ ç¾¤å•Šï¼ä¸€å®šè¦åŠ å•Šï¼

  - name: ğŸ“œ QF-Wonder ä»‹ç»é¡µ
    url: https://blog.qianf.fun/archives/3e3886de.html
    about: å—¯ï¼Ÿè¿™çœŸçš„æ˜¯å…»è€æœå—ï¼Ÿ

  - name: âŒ¨ï¸ Minecraft Mod Wiki
    url: https://mcmod.cn/
    about: æœåŠ¡å™¨ä¸­å¤§å¤§å°å°ä¸‰ç™¾ä½™ä¸ªæ¨¡ç»„ï¼Œåœ¨è¿™é‡Œéƒ½å¯ä»¥æŸ¥åˆ°ï¼ˆå¤§æ¦‚ï¼‰
